### ISSUE TITLE
Error When Code is Ran

### ISSUE THREAD

**Issue by LynetteCullens** [mpaulse/koinlyxp#2]
Traceback (most recent call last):
  File "C:\Users\breyo\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\breyo\AppData\Roaming\Python\Python311\Scripts\koinlyxp.exe\__main__.py", line 7, in <module>
  File "C:\Users\breyo\AppData\Roaming\Python\Python311\site-packages\koinlyxp\exporter.py", line 176, in run
    user_info = get_user_info(http_session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\breyo\AppData\Roaming\Python\Python311\site-packages\koinlyxp\exporter.py", line 67, in get_user_info
    rsp_body = http_session.get(f"{BASE_API_URL}/sessions").json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\breyo\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andwan0** [comment]
I get this too.
It seems the http session is returning blank.

**Comment by LynetteCullens** [comment]
I ended up just using a console command in chrome.
